# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: R
sudo: false
cache: packages
warnings_are_errors: false

#env
env:
  global:
  - MAKEFLAGS="-j 2"
  - WARNINGS_ARE_ERRORS=1
  - R_CHECK_ARGS="--as-cran"

#notifications
notifications:
  email:
    on_success: true
    on_failure: true

#after_success
after_success:
  - Rscript -e 'covr::codecov()'
